const materials = [
  {
    id: "copper",
    name: "銅",
    symbol: "HG=F",
    stooqSymbol: "HG.F",
    stooqPriceFactor: 0.01,
    category: "工業金屬",
    exchange: "COMEX",
    unit: "USD/lb",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - COMEX Copper Futures",
    fallbackSource: "Stooq - HG.F",
    usage: "銅排、電線、端子、散熱與機構件成本參考",
  },
  {
    id: "aluminum",
    name: "鋁",
    symbol: "ALI=F",
    category: "工業金屬",
    exchange: "Yahoo Finance Aluminum Futures",
    unit: "USD/metric ton",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Aluminum Futures",
    usage: "鋁擠型、鋁板、壓鑄與 CNC 鋁件成本參考",
  },
  {
    id: "steel-hrc",
    name: "熱軋鋼捲",
    symbol: "HRC=F",
    category: "鋼鐵",
    exchange: "U.S. Midwest HRC",
    unit: "USD/short ton",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - U.S. Midwest HRC Steel Futures",
    usage: "鈑金、鋼構、沖壓件與板材成本參考",
  },
  {
    id: "iron-ore",
    name: "鐵礦砂",
    symbol: "TIO=F",
    category: "鋼鐵",
    exchange: "Yahoo Finance Iron Ore Futures",
    unit: "USD/metric ton",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Iron Ore Futures",
    usage: "鋼材成本趨勢參考，不等於實際鋼板採購價",
  },
  {
    id: "wti-oil",
    name: "WTI 原油",
    symbol: "CL=F",
    stooqSymbol: "CL.F",
    category: "能源",
    exchange: "NYMEX",
    unit: "USD/barrel",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - WTI Crude Oil Futures",
    fallbackSource: "Stooq - CL.F",
    usage: "塑膠、橡膠、油品、運輸成本趨勢參考",
  },
  {
    id: "brent-oil",
    name: "Brent 原油",
    symbol: "BZ=F",
    category: "能源",
    exchange: "ICE Brent",
    unit: "USD/barrel",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Brent Crude Oil Futures",
    usage: "國際原油與石化成本趨勢參考",
  },
  {
    id: "natural-gas",
    name: "天然氣",
    symbol: "NG=F",
    stooqSymbol: "NG.F",
    category: "能源",
    exchange: "NYMEX",
    unit: "USD/MMBtu",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Natural Gas Futures",
    fallbackSource: "Stooq - NG.F",
    usage: "能源、熱處理、鍋爐、化工成本趨勢參考",
  },
  {
    id: "gold",
    name: "黃金",
    symbol: "GC=F",
    stooqSymbol: "GC.F",
    category: "貴金屬",
    exchange: "COMEX",
    unit: "USD/troy oz",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Gold Futures",
    fallbackSource: "Stooq - GC.F",
    usage: "鍍金、電子接點、貴金屬成本趨勢參考",
  },
  {
    id: "silver",
    name: "白銀",
    symbol: "SI=F",
    stooqSymbol: "SI.F",
    stooqPriceFactor: 0.01,
    category: "貴金屬",
    exchange: "COMEX",
    unit: "USD/troy oz",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Silver Futures",
    fallbackSource: "Stooq - SI.F",
    usage: "導電材料、焊料、鍍銀件成本趨勢參考",
  },
  {
    id: "platinum",
    name: "鉑金",
    symbol: "PL=F",
    stooqSymbol: "PL.F",
    category: "貴金屬",
    exchange: "NYMEX",
    unit: "USD/troy oz",
    currency: "USD",
    conversionFactor: 1,
    source: "Yahoo Finance - Platinum Futures",
    fallbackSource: "Stooq - PL.F",
    usage: "觸媒、感測器、特殊電極成本趨勢參考",
  },
  {
    id: "corn",
    name: "玉米",
    symbol: "ZC=F",
    stooqSymbol: "ZC.F",
    category: "農產品",
    exchange: "CBOT",
    unit: "US cents/bushel",
    currency: "USD",
    conversionFactor: 0.01,
    source: "Yahoo Finance - Corn Futures",
    fallbackSource: "Stooq - ZC.F",
    usage: "食品、飼料、澱粉與生質材料成本趨勢參考",
  },
  {
    id: "soybean",
    name: "黃豆",
    symbol: "ZS=F",
    stooqSymbol: "ZS.F",
    category: "農產品",
    exchange: "CBOT",
    unit: "US cents/bushel",
    currency: "USD",
    conversionFactor: 0.01,
    source: "Yahoo Finance - Soybean Futures",
    fallbackSource: "Stooq - ZS.F",
    usage: "食品、油脂、飼料與生質材料成本趨勢參考",
  },
  {
    id: "coffee",
    name: "咖啡",
    symbol: "KC=F",
    stooqSymbol: "KC.F",
    category: "農產品",
    exchange: "ICE Coffee",
    unit: "US cents/lb",
    currency: "USD",
    conversionFactor: 0.01,
    source: "Yahoo Finance - Coffee Futures",
    fallbackSource: "Stooq - KC.F",
    usage: "食品原料成本趨勢參考",
  },
  {
    id: "cotton",
    name: "棉花",
    symbol: "CT=F",
    stooqSymbol: "CT.F",
    category: "纖維",
    exchange: "ICE Cotton",
    unit: "US cents/lb",
    currency: "USD",
    conversionFactor: 0.01,
    source: "Yahoo Finance - Cotton Futures",
    fallbackSource: "Stooq - CT.F",
    usage: "紡織、包材、耗材成本趨勢參考",
  },
];

module.exports = {
  materials,
};
